definitions:
  api.createAccountRequest:
    properties:
      currency:
        enum:
        - USD
        - EUR
        - GBP
        - CNY
        type: string
      owner:
        type: string
    required:
    - currency
    - owner
    type: object
info:
  contact: {}
  description: A Golang and gin API template
  title: simple bank API
  version: "1.0"
paths:
  /api/v1/accounts:
    post:
      description: Takes an account json and store in DB, Returned saved json.
      parameters:
      - description: account json
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/api.createAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: create account
      tags:
      - accounts
swagger: "2.0"
